name: Deployment to server
on:
    push:
        branches: [beta]

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: rjstone/discord-webhook-notify@v1
              with:
                  severity: info
                  details: Deployment started...
                  webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - run: |
                  touch .env
                  echo "APP_ENV=beta" >> .env
                  echo "BASE_URL=https://beta.makebetter.app" >> .env
                  echo "API_BASE_URL=https://api.umaestro.fr" >> .env
                  echo "GIT_SHA=${{ github.sha }}" >> .env
                  npm install
                  npm run build
                  cp .env .output/server/.env
                  tar -czf "${GITHUB_SHA}".tar.gz .output
                  sudo mv "${GITHUB_SHA}".tar.gz /var/www/beta_makebetter
            - uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: debian
                  key: ${{ secrets.SSH_KEY }}
                  port: 22
                  script: |
                      cd /var/www/beta_makebetter
                      rm -rf .output
                      mkdir .output
                      tar -xzf "${{ github.sha }}".tar.gz -C .output
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - run: |
                  pm2 delete makebetter-beta
                  cd /var/www/.output/server
                  pm2 start index.mjs --name "makebetter-beta"

            - uses: rjstone/discord-webhook-notify@v1
              if: success()
              with:
                  severity: info
                  details: Nouvelle version déployée avec succès! 🪄
                  webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
            - uses: rjstone/discord-webhook-notify@v1
              if: failure()
              with:
                  severity: error
                  details: Une erreur est survenue...
                  webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
            - uses: rjstone/discord-webhook-notify@v1
              if: cancelled()
              with:
                  severity: warn
                  details: Déploiement annulé...
                  webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
